meta_product_name: "LACTY"
meta_title: "LACTY - Même les licornes sont intolérantes au lactose!"
meta_description: "Découvrez la présence de lactose dans vos aliments en quelques clics"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
